---
title: "PROCESSOS - PROPLAN"
author: Asplan
runtime: shiny # shiny, shinyrmd
output: 
  flexdashboard::flex_dashboard:
    storyboard: true    # colocar mapa no dashboard
    logo: logo.png
    favicon: ufs.png
    orientation: columns # columns, rows
    vertical_layout: fill # scroll, fill
    social: menu # ["Twitter", "facebook", "linkedin", "whatsapp", "telegram"]
    navbar:
     # - { title: "Sobre Mim", href: "https://proplan.ufs.br/pagina/98", align: right }
      - { icon: fa-address-card, href: "https://proplan.ufs.br/pagina/98", align: right }
    source_code: embed # COMPARTILHAR CÓDIGOS COM OUTRAS PESSOAS
    #theme: united
    theme:
      bg: "#363636" # "#FDF7F7" # "#101010" (PLANO DE FUNDO)
      fg: "#eee" # "white" , "#FDF7F7" , "#2F4F4F" # COR DA LETRA (PIRMEIRO PLANO)
      primary: "#000099" #"#000099", "#000000", "#ED79F9", "#3ADAC6" # ONDE FICA O TITULO
      navbar-bg: "#006400" # "#3ADAC6" # COR DA PARTE INTERNA DAS INFORMAÇÕES
      base_font: 
        google: Ubuntu #"Merriweather" # "Sree Krushnadevaraya", "Prompt", "Newsreader", "Times New Roman"
      heading_font:
        google: Ubuntu
      code_font: 
        google: Ubuntu # "Merriweather" # "Newsreader", "JetBrains Mono" "Times New Roman"
      font-size-base: "0.90rem"
      version: 4
---


```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(rmarkdown)
library(htmlTable)
library(htmltools)
library(markdown)
library(dplyr)
library(tidyr)
library(ggplot2)
#library(xlsx)
library(readr)
library(readxl)
library(DT)
library(knitr)
library(shiny)
library(dashboardthemes)
library(purrr)
library(fontawesome) # colocar icones nos títulos das abas
library(rbokeh)
library(bslib)
library(plotly)
library(htmlwidgets)
library(digest)
library(bit)
#library(bubbles)
library(bubblyr)
library(dygraphs)
library(mgcv)
library(plotly)
library(leaflet)
#library(pacman)
# pacman::p_load(rmarkdown,ggplot2,htmlTable,htmltools,markdown,dplyr,tidyr,readr,readxl,DT,knitr,shiny,dashboardthemes,purrr,rbokeh,bslib,plotly,htmlwidgets,digest,bit,bubblyr,dygraphs,mgcv,leaflet)

# options(scipen = 999)

# SETEMBRO:

#tramitacao_set1 <- read_excel("(PROPLAN) Controle de Processos 2022.xlsx", sheet = "SETEMBRO-2022", skip = 2)


tramitacao_set <- read.csv('https://raw.githubusercontent.com/wilasfarias/PROCESSOS/main/Processo_2022/PROPLAN_SETEMBRO.csv', sep = ";", fileEncoding = "UTF-8", header = TRUE, skip = 2)

tramitacao_set <- rename(tramitacao_set, 
                         "NÚMERO DO PROCESSO (SIPAC/SEI!)" = "NÚMERO.DO.PROCESSO..SIPAC.SEI..",
                         "DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)" = "DATA.DE.ENTRADA..RECEBIMENTO.OU.ABERTURA.",
                         "RESPONSÁVEL PELO RECEBIMENTO / ABERTURA" = "RESPONSÁVEL.PELO.RECEBIMENTO...ABERTURA",
                         "LOCAL DE ORIGEM" = "LOCAL.DE.ORIGEM",
                         "ASSUNTO DETALHADO (SIPAC / SEI!)" = "ASSUNTO.DETALHADO..SIPAC...SEI..",
                         "DESPACHO / AÇÃO A SER EXECUTADA (RESUMIDO)" = "DESPACHO...AÇÃO.A.SER.EXECUTADA..RESUMIDO.",
                         "PROCESSO SOBRESTADO?" = "PROCESSO.SOBRESTADO.",
                         "MOTIVO DO SOBRESTAMENTO" = "MOTIVO.DO.SOBRESTAMENTO",
                         "TEMPO DE SOBRESTAMENTO (DIAS)" = "TEMPO.DE.SOBRESTAMENTO..DIAS.",
                         "DATA DE ENCAMINHAMENTO (SAÍDA)" = "DATA.DE.ENCAMINHAMENTO..SAÍDA.",
                         "RESPONSÁVEL PELO ENCAMINHAMENTO (SAÍDA)" = "RESPONSÁVEL.PELO.ENCAMINHAMENTO..SAÍDA.",
                         "DESPACHO / AÇÃO DE ENCAMINHAMENTO (RESUMIDO)" = "DESPACHO...AÇÃO.DE.ENCAMINHAMENTO..RESUMIDO.",
                         "LOCAL DE DESTINO" = "LOCAL.DE.DESTINO",
                         "TEMPO DO PROCESSO NO SETOR (DIAS)" = "TEMPO.DO.PROCESSO.NO.SETOR..DIAS."
)


tramitacao_set$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)` <- as.Date(tramitacao_set$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`, '%d/%m/%Y')

tramitacao_set$`DATA DE ENCAMINHAMENTO (SAÍDA)` <- as.Date(tramitacao_set$`DATA DE ENCAMINHAMENTO (SAÍDA)`, '%d/%m/%Y')

# eliminar dados missing
tramitacao_set <- tramitacao_set[!is.na(tramitacao_set[,1]),]
tramitacao_set <- tramitacao_set[!is.na(tramitacao_set[,2]),]

tramitacao_set$`TEMPO DE SOBRESTAMENTO (DIAS)` <- as.double(tramitacao_set$`TEMPO DE SOBRESTAMENTO (DIAS)`)

tramitacao_set$`TEMPO DO PROCESSO NO SETOR (DIAS)` <- as.double(tramitacao_set$`TEMPO DO PROCESSO NO SETOR (DIAS)`)

tramitacao_set$`MES` <- as.factor(9)
tramitacao_set$`ANO` <- "2022"

tramitacao_set <- as.data.frame(tramitacao_set)

tramitacao_set[,1] <- as.factor(tramitacao_set[,1])
tramitacao_set[,13] <- as.factor(tramitacao_set[,13])

tramitacao_set[,14] <- difftime(tramitacao_set[,10], as.Date(tramitacao_set[,2]), units = "days")-tramitacao_set[,9]

tramitacao_set <- tramitacao_set %>% arrange(tramitacao_set, tramitacao_set[,14])


#tramitacao_set <- select(tramitacao_set, "MES", "ANO", `NÚMERO DO PROCESSO (SIPAC/SEI!)`:`TEMPO DO PROCESSO NO SETOR (DIAS)`)


# colocando NAs nos dados faltantes de destino:
tramitacao_set$`LOCAL DE DESTINO` <- as.character(tramitacao_set$`LOCAL DE DESTINO`)

tramitacao_set$`LOCAL DE DESTINO`[is.na(tramitacao_set$`LOCAL DE DESTINO`)] <- "NA"


tramitacao_set$`LOCAL DE DESTINO`[tramitacao_set$`LOCAL DE DESTINO` == ""] <- "NA"


tramitacao_set$`LOCAL DE DESTINO` <- as.factor(tramitacao_set$`LOCAL DE DESTINO`)


# colocando zero (0) no lugar nos missings de duração no setor:
tramitacao_set$`TEMPO DO PROCESSO NO SETOR (DIAS)`[is.na(tramitacao_set$`TEMPO DO PROCESSO NO SETOR (DIAS)`)] <- as.Date("2022-09-30")-as.Date(tramitacao_set$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`)

#glimpse(tramitacao_set)
#----------------------------------------------------------------------------#

# OUTUBRO:

#tramitacao_out <- read_excel("(PROPLAN) Controle de Processos 2022.xlsx", sheet = "OUTUBRO-2022", skip = 2)


tramitacao_out <- read.csv('https://raw.githubusercontent.com/wilasfarias/PROCESSOS/main/Processo_2022/PROPLAN_OUTUBRO.csv', sep = ";", fileEncoding = "UTF-8", header = TRUE)

tramitacao_out <- rename(tramitacao_out, 
                         "NÚMERO DO PROCESSO (SIPAC/SEI!)" = "NÚMERO.DO.PROCESSO..SIPAC.SEI..",
                         "DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)" = "DATA.DE.ENTRADA..RECEBIMENTO.OU.ABERTURA.",
                         "RESPONSÁVEL PELO RECEBIMENTO / ABERTURA" = "RESPONSÁVEL.PELO.RECEBIMENTO...ABERTURA",
                         "LOCAL DE ORIGEM" = "LOCAL.DE.ORIGEM",
                         "ASSUNTO DETALHADO (SIPAC / SEI!)" = "ASSUNTO.DETALHADO..SIPAC...SEI..",
                         "DESPACHO / AÇÃO A SER EXECUTADA (RESUMIDO)" = "DESPACHO...AÇÃO.A.SER.EXECUTADA..RESUMIDO.",
                         "PROCESSO SOBRESTADO?" = "PROCESSO.SOBRESTADO.",
                         "MOTIVO DO SOBRESTAMENTO" = "MOTIVO.DO.SOBRESTAMENTO",
                         "TEMPO DE SOBRESTAMENTO (DIAS)" = "TEMPO.DE.SOBRESTAMENTO..DIAS.",
                         "DATA DE ENCAMINHAMENTO (SAÍDA)" = "DATA.DE.ENCAMINHAMENTO..SAÍDA.",
                         "RESPONSÁVEL PELO ENCAMINHAMENTO (SAÍDA)" = "RESPONSÁVEL.PELO.ENCAMINHAMENTO..SAÍDA.",
                         "DESPACHO / AÇÃO DE ENCAMINHAMENTO (RESUMIDO)" = "DESPACHO...AÇÃO.DE.ENCAMINHAMENTO..RESUMIDO.",
                         "LOCAL DE DESTINO" = "LOCAL.DE.DESTINO",
                         "TEMPO DO PROCESSO NO SETOR (DIAS)" = "TEMPO.DO.PROCESSO.NO.SETOR..DIAS."
)


tramitacao_out$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)` <- as.Date(tramitacao_out$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`, '%d/%m/%Y')

tramitacao_out$`DATA DE ENCAMINHAMENTO (SAÍDA)` <- as.Date(tramitacao_out$`DATA DE ENCAMINHAMENTO (SAÍDA)`, '%d/%m/%Y')

# eliminar dados missing
tramitacao_out <- tramitacao_out[!is.na(tramitacao_out[,1]),]
tramitacao_out <- tramitacao_out[!is.na(tramitacao_out[,2]),]

tramitacao_out$`TEMPO DE SOBRESTAMENTO (DIAS)` <- as.double(tramitacao_out$`TEMPO DE SOBRESTAMENTO (DIAS)`)

tramitacao_out$`TEMPO DO PROCESSO NO SETOR (DIAS)` <- as.double(tramitacao_out$`TEMPO DO PROCESSO NO SETOR (DIAS)`)


tramitacao_out$`MES` <- as.factor(10)
tramitacao_out$`ANO` <- "2022"

tramitacao_out <- as.data.frame(tramitacao_out)

tramitacao_out[,1] <- as.factor(tramitacao_out[,1])
tramitacao_out[,13] <- as.factor(tramitacao_out[,13])

tramitacao_out[,14] <- difftime(tramitacao_out[,10], as.Date(tramitacao_out[,2]), units = "days")-tramitacao_out[,9]

tramitacao_out <- tramitacao_out %>% arrange(tramitacao_out, tramitacao_out[,14])


#tramitacao_out <- select(tramitacao_out, "MES", "ANO", `NÚMERO DO PROCESSO (SIPAC/SEI!)`:`TEMPO DO PROCESSO NO SETOR (DIAS)`)


# colocando NAs nos dados faltantes de destino:
tramitacao_out$`LOCAL DE DESTINO` <- as.character(tramitacao_out$`LOCAL DE DESTINO`)

tramitacao_out$`LOCAL DE DESTINO`[is.na(tramitacao_out$`LOCAL DE DESTINO`)] <- "NA"

tramitacao_out$`LOCAL DE DESTINO`[tramitacao_out$`LOCAL DE DESTINO` == ""] <- "NA"

tramitacao_out$`LOCAL DE DESTINO` <- as.factor(tramitacao_out$`LOCAL DE DESTINO`)


# colocando zero (0) no lugar nos missings de duração no setor:
tramitacao_out$`TEMPO DO PROCESSO NO SETOR (DIAS)`[is.na(tramitacao_out$`TEMPO DO PROCESSO NO SETOR (DIAS)`)] <- as.Date("2022-10-31")-as.Date(tramitacao_out$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`)

#glimpse(tramitacao_out)

#Sys.Date()


#------------------------------------------------------------------------------------#

# NOVEMBRO:

#tramitacao_nov <- read_excel("(PROPLAN) Controle de Processos 2022.xlsx", sheet = "NOVEMBRO-2022", skip = 2)


tramitacao_nov <- read.csv('https://raw.githubusercontent.com/wilasfarias/PROCESSOS/main/Processo_2022/PROPLAN_NOVEMBRO.csv', sep = ";", fileEncoding = "UTF-8", header = TRUE, skip = 2)

tramitacao_nov <- rename(tramitacao_nov, 
                         "NÚMERO DO PROCESSO (SIPAC/SEI!)" = "NÚMERO.DO.PROCESSO..SIPAC.SEI..",
                         "DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)" = "DATA.DE.ENTRADA..RECEBIMENTO.OU.ABERTURA.",
                         "RESPONSÁVEL PELO RECEBIMENTO / ABERTURA" = "RESPONSÁVEL.PELO.RECEBIMENTO...ABERTURA",
                         "LOCAL DE ORIGEM" = "LOCAL.DE.ORIGEM",
                         "ASSUNTO DETALHADO (SIPAC / SEI!)" = "ASSUNTO.DETALHADO..SIPAC...SEI..",
                         "DESPACHO / AÇÃO A SER EXECUTADA (RESUMIDO)" = "DESPACHO...AÇÃO.A.SER.EXECUTADA..RESUMIDO.",
                         "PROCESSO SOBRESTADO?" = "PROCESSO.SOBRESTADO.",
                         "MOTIVO DO SOBRESTAMENTO" = "MOTIVO.DO.SOBRESTAMENTO",
                         "TEMPO DE SOBRESTAMENTO (DIAS)" = "TEMPO.DE.SOBRESTAMENTO..DIAS.",
                         "DATA DE ENCAMINHAMENTO (SAÍDA)" = "DATA.DE.ENCAMINHAMENTO..SAÍDA.",
                         "RESPONSÁVEL PELO ENCAMINHAMENTO (SAÍDA)" = "RESPONSÁVEL.PELO.ENCAMINHAMENTO..SAÍDA.",
                         "DESPACHO / AÇÃO DE ENCAMINHAMENTO (RESUMIDO)" = "DESPACHO...AÇÃO.DE.ENCAMINHAMENTO..RESUMIDO.",
                         "LOCAL DE DESTINO" = "LOCAL.DE.DESTINO",
                         "TEMPO DO PROCESSO NO SETOR (DIAS)" = "TEMPO.DO.PROCESSO.NO.SETOR..DIAS."
)


tramitacao_nov$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)` <- as.Date(tramitacao_nov$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`, '%d/%m/%Y')

tramitacao_nov$`DATA DE ENCAMINHAMENTO (SAÍDA)` <- as.Date(tramitacao_nov$`DATA DE ENCAMINHAMENTO (SAÍDA)`, '%d/%m/%Y')

# eliminar dados missing
tramitacao_nov <- tramitacao_nov[!is.na(tramitacao_nov[,1]),]
tramitacao_nov <- tramitacao_nov[!is.na(tramitacao_nov[,2]),]

tramitacao_nov$`TEMPO DE SOBRESTAMENTO (DIAS)` <- as.double(tramitacao_nov$`TEMPO DE SOBRESTAMENTO (DIAS)`)

tramitacao_nov$`TEMPO DO PROCESSO NO SETOR (DIAS)` <- as.double(tramitacao_nov$`TEMPO DO PROCESSO NO SETOR (DIAS)`)


tramitacao_nov$`MES` <- as.factor(11)
tramitacao_nov$`ANO` <- "2022"

tramitacao_nov <- as.data.frame(tramitacao_nov)

tramitacao_nov[,1] <- as.factor(tramitacao_nov[,1])
tramitacao_nov[,13] <- as.factor(tramitacao_nov[,13])

tramitacao_nov[,14] <- difftime(tramitacao_nov[,10], as.Date(tramitacao_nov[,2]), units = "days")-tramitacao_nov[,9]

tramitacao_nov <- tramitacao_nov %>% arrange(tramitacao_nov, tramitacao_nov[,14])


#tramitacao_nov <- select(tramitacao_nov, "MES", "ANO", `NÚMERO DO PROCESSO (SIPAC/SEI!)`:`TEMPO DO PROCESSO NO SETOR (DIAS)`)


# colocando NAs nos dados faltantes de destino:
tramitacao_nov$`LOCAL DE DESTINO` <- as.character(tramitacao_nov$`LOCAL DE DESTINO`)

tramitacao_nov$`LOCAL DE DESTINO`[is.na(tramitacao_nov$`LOCAL DE DESTINO`)] <- "NA"

tramitacao_nov$`LOCAL DE DESTINO`[tramitacao_nov$`LOCAL DE DESTINO` == ""] <- "NA"

tramitacao_nov$`LOCAL DE DESTINO` <- as.factor(tramitacao_nov$`LOCAL DE DESTINO`)
tramitacao_nov$`MOTIVO DO SOBRESTAMENTO` <- as.character(tramitacao_nov$`MOTIVO DO SOBRESTAMENTO`)

# colocando zero (0) no lugar nos missings de duração no setor, depois alterar para o fechamento do mes:
tramitacao_nov$`TEMPO DO PROCESSO NO SETOR (DIAS)`[is.na(tramitacao_nov$`TEMPO DO PROCESSO NO SETOR (DIAS)`)] <- Sys.Date()-as.Date(tramitacao_nov$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`)

# Sys.Date()
# as.Date("2022-11-30")

#--------------------------------------------------------------------------------#

# DEZEMBRO:

#tramitacao_dez <- read_excel("(PROPLAN) Controle de Processos 2022.xlsx", sheet = "DEZEMBRO-2022", skip = 2)

#tramitacao_dez <- read.csv('https://raw.githubusercontent.com/wilasfarias/PROCESSOS/main/Processo_2022/PROPLAN_DEZEMBRO.csv', sep = ";", fileEncoding = "UTF-8", header = TRUE, skip = 2)

tramitacao_dez <- read.csv('https://raw.githubusercontent.com/wilasfarias/PROCESSOS/main/Processo_2022/PROPLAN_DEZEMBRO.csv',
                           sep = ";", 
                           fileEncoding = "Latin1", # "UTF-8", 
                           fill = TRUE,
                           header = TRUE, 
                           skip = 2)

tramitacao_dez <- rename(tramitacao_dez, 
                         "NÚMERO DO PROCESSO (SIPAC/SEI!)" = "NÚMERO.DO.PROCESSO..SIPAC.SEI..",
                         "DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)" = "DATA.DE.ENTRADA..RECEBIMENTO.OU.ABERTURA.",
                         "RESPONSÁVEL PELO RECEBIMENTO / ABERTURA" = "RESPONSÁVEL.PELO.RECEBIMENTO...ABERTURA",
                         "LOCAL DE ORIGEM" = "LOCAL.DE.ORIGEM",
                         "ASSUNTO DETALHADO (SIPAC / SEI!)" = "ASSUNTO.DETALHADO..SIPAC...SEI..",
                         "DESPACHO / AÇÃO A SER EXECUTADA (RESUMIDO)" = "DESPACHO...AÇÃO.A.SER.EXECUTADA..RESUMIDO.",
                         "PROCESSO SOBRESTADO?" = "PROCESSO.SOBRESTADO.",
                         "MOTIVO DO SOBRESTAMENTO" = "MOTIVO.DO.SOBRESTAMENTO",
                         "TEMPO DE SOBRESTAMENTO (DIAS)" = "TEMPO.DE.SOBRESTAMENTO..DIAS.",
                         "DATA DE ENCAMINHAMENTO (SAÍDA)" = "DATA.DE.ENCAMINHAMENTO..SAÍDA.",
                         "RESPONSÁVEL PELO ENCAMINHAMENTO (SAÍDA)" = "RESPONSÁVEL.PELO.ENCAMINHAMENTO..SAÍDA.",
                         "DESPACHO / AÇÃO DE ENCAMINHAMENTO (RESUMIDO)" = "DESPACHO...AÇÃO.DE.ENCAMINHAMENTO..RESUMIDO.",
                         "LOCAL DE DESTINO" = "LOCAL.DE.DESTINO",
                         "TEMPO DO PROCESSO NO SETOR (DIAS)" = "TEMPO.DO.PROCESSO.NO.SETOR..DIAS."
)


tramitacao_dez$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)` <- as.Date(tramitacao_dez$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`, '%d/%m/%Y')

tramitacao_dez$`DATA DE ENCAMINHAMENTO (SAÍDA)` <- as.Date(tramitacao_dez$`DATA DE ENCAMINHAMENTO (SAÍDA)`, '%d/%m/%Y')

# ativar assim que o mês for utilizado
tramitacao_dez$`MES` <- as.factor(12)
tramitacao_dez$`ANO` <- "2022"

# eliminar dados missing
tramitacao_dez <- tramitacao_dez[!is.na(tramitacao_dez[,1]),]
tramitacao_dez <- tramitacao_dez[!is.na(tramitacao_dez[,2]),]

tramitacao_dez$`TEMPO DE SOBRESTAMENTO (DIAS)` <- as.double(tramitacao_dez$`TEMPO DE SOBRESTAMENTO (DIAS)`)

tramitacao_dez$`TEMPO DO PROCESSO NO SETOR (DIAS)` <- as.double(tramitacao_dez$`TEMPO DO PROCESSO NO SETOR (DIAS)`)

tramitacao_dez <- as.data.frame(tramitacao_dez)

tramitacao_dez[,1] <- as.factor(tramitacao_dez[,1])
tramitacao_dez[,13] <- as.factor(tramitacao_dez[,13])

tramitacao_dez[,14] <- difftime(tramitacao_dez[,10], as.Date(tramitacao_dez[,2]), units = "days")-tramitacao_dez[,9]

tramitacao_dez <- tramitacao_dez %>% arrange(tramitacao_dez, tramitacao_dez[,14])


#tramitacao_dez <- select(tramitacao_dez, "MES", "ANO", `NÚMERO DO PROCESSO (SIPAC/SEI!)`:`TEMPO DO PROCESSO NO SETOR (DIAS)`)


# colocando NAs nos dados faltantes de destino:
tramitacao_dez$`LOCAL DE DESTINO` <- as.character(tramitacao_dez$`LOCAL DE DESTINO`)

tramitacao_dez$`LOCAL DE DESTINO`[is.na(tramitacao_dez$`LOCAL DE DESTINO`)] <- "NA"

tramitacao_dez$`LOCAL DE DESTINO`[tramitacao_dez$`LOCAL DE DESTINO` == ""] <- "NA"

tramitacao_dez$`LOCAL DE DESTINO` <- as.factor(tramitacao_dez$`LOCAL DE DESTINO`)


# colocando zero (0) no lugar nos missings de duração no setor, depois alterar para o fechamento do mes:
tramitacao_dez$`TEMPO DO PROCESSO NO SETOR (DIAS)`[is.na(tramitacao_dez$`TEMPO DO PROCESSO NO SETOR (DIAS)`)] <- Sys.Date()-as.Date(tramitacao_dez$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`)

# Sys.Date()
# as.Date("2022-12-31"

#------------------------------------------------------------------------------------#

# JANEIRO:



#----------------------------------------------------------#
# JUNTAR BASE DE DADOS:
tramitacao <- tramitacao_set %>% full_join(tramitacao_out)
tramitacao <- tramitacao %>% full_join(tramitacao_nov)
# tramitacao <- tramitacao %>% full_join(tramitacao_dez)


# colocar os setores
a <- tramitacao %>% select(`LOCAL DE ORIGEM`) %>% distinct()

b <- tramitacao[!is.na(tramitacao$`LOCAL DE DESTINO`),] %>% 
  select(`LOCAL DE DESTINO`) %>% 
  distinct()

(table_periodo <- full_join(a, b, by = c("LOCAL DE ORIGEM"="LOCAL DE DESTINO")))

table_periodo <- rename(table_periodo, "setor" = "LOCAL DE ORIGEM")
(table_periodo$dias <- c(1:as.numeric(count(table_periodo))))

table_periodo <- table_periodo %>% arrange(setor)

# filtro da aba de "ACOMPANHAMENTO":
month_list <- as.list(1:12) %>%
  set_names(month.name)
  
month_list$`All Year` <- 99


# dados aba "TODOS OS PROCESSOS":
# encontrar as somas de processos faltantes e os que foi enviados:
missing <- tramitacao %>% filter(`LOCAL DE DESTINO` == "NA")
progresso <- tramitacao %>% filter(`LOCAL DE DESTINO` != "NA")


movimentacao <- tramitacao

movimentacao$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)` <- as.character.Date(movimentacao$`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`)

movimentacao$`DATA DE ENCAMINHAMENTO (SAÍDA)` <- as.character.Date(movimentacao$`DATA DE ENCAMINHAMENTO (SAÍDA)`)

movimentacao <- movimentacao %>% 
  select(MES, ANO, `NÚMERO DO PROCESSO (SIPAC/SEI!)`:`TEMPO DO PROCESSO NO SETOR (DIAS)`)

```

# ACOMPANHAMENTO {data-icon="fa-table"}

## Colmn {.sidebar} {data-width=100}
```{r}
selectInput(inputId = "setor",
            label = "Local de Destino:", 
            choices = unique(table_periodo$setor),
            selected = "NA")

sliderInput("dias", "Dias:", value = 30, min = 0, max = 60)
```

```{r}
selectInput(
  inputId = "month",
  label = "Month:",
  choices = month_list,
  selected = 99,
  size = 13,
  selectize = FALSE
  )
```

### Recebidos
```{r}
renderValueBox({
total <- tramitacao %>% 
  select(MES) %>% 
  filter(input$month == MES)

valueBox(count(total), 
         icon = "fa-table", 
         color = "#3275B8")
  })

```


## Colmn {data-width=1000}
### Processos
```{r}
renderTable({
tramitacao %>% filter(`LOCAL DE DESTINO` == input$setor, `TEMPO DO PROCESSO NO SETOR (DIAS)` <= input$dias, `MES` == input$month) %>% 
    select(`NÚMERO DO PROCESSO (SIPAC/SEI!)`, `LOCAL DE ORIGEM`, `ASSUNTO DETALHADO (SIPAC / SEI!)`, `MOTIVO DO SOBRESTAMENTO`, `TEMPO DE SOBRESTAMENTO (DIAS)`, `DESPACHO / AÇÃO DE ENCAMINHAMENTO (RESUMIDO)`, `LOCAL DE DESTINO`, `TEMPO DO PROCESSO NO SETOR (DIAS)`)

})

```


# TODOS OS PROCESSOS {data-icon="fa-table"}

## Colmn {.sidebar} {data-width=100}
### Processos à Enviar 
```{r}
valueBox(count(missing), icon = "fa-pencil", color = "#88BBEE")

```

### Enviados
```{r}
valueBox(count(progresso), icon = "fa-table", color = "#4095EB")

```

### Recebidos
```{r}
valueBox(count(tramitacao), icon = "fa-table", color = "#3275B8")
```

## Colmn {.tabset data-width=700}
### Processos
```{r}
DT::renderDataTable({
  DT::datatable(movimentacao, 
                editable = 'cell',
                options = list(
                  searching = TRUE,
                  pageLength = 1000,
                  lengthMenu = 1000)
                ) %>% 
    formatStyle('LOCAL DE DESTINO', color = 'red', fontWeight = 'bold')
})
```


### Gráficos
```{r}
# agrupar dados em uma tela
# FIGURAS {data-table=row data-icon="fa-chart-line" data-navmenu="GRÁFICOS"}
# # FIGURAS {data-icon="fa-chart-line"} {.tabset}

renderPlotly({
#tramitacao %>% filter(`NÚMERO DO PROCESSO (SIPAC/SEI!)` == input$processo) %>% 
  
grafico <- ggplot(tramitacao, 
                  aes(x=`DATA DE ENTRADA (RECEBIMENTO OU ABERTURA)`, y=`TEMPO DO PROCESSO NO SETOR (DIAS)`, color = `NÚMERO DO PROCESSO (SIPAC/SEI!)`)) + 
  geom_point() +
  theme(panel.background = element_rect(fill = "#363636"),
        plot.background = element_rect(fill = "#363636"),
        text = element_text(color="white"),                # texto do gráfico (tílos ou elementos da legenda)
        axis.text.x = element_text(color="white"),         # texto os eixos do gráfico
        axis.text.y  = element_text(color="white"),        # texto do eixo Y do gráfico
        #title = element_text(color="black"),               # títulos do gráfico
        legend.title = element_text(color="white"),        # cor da fonte da legenda
        legend.text = element_text(color="white"),         # cor da fonte da legenda interna. 
        legend.background = element_rect(fill="#363636"),  # colocar cor de fundo da legenda
        )

ggplotly(grafico)

})
```


### Universidade Federal de Sergipe

```{r}
leaflet() %>%
  addTiles() %>%
  addMarkers(lng=-37.099043, lat=-10.925129, popup="PROPLAN")

```


